services:
  mysql-db:
    image: mysql:8.0
    container_name: anyquestion-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: anyquestion_db
    ports:
      - "3306:3306"
    volumes:
      - anyquestion_db_data:/var/lib/mysql
volumes:
 anyquestion_db_data:
  
